#!/usr/bin/env bash
#comment
function subdomain_details() {
	result=$(dig "$1" | grep -A1 'ANSWER SECTION:' | tail -1)
	subdomain=$(awk '{print $1}' <<< "$result")
	record_type=$(awk '{print $4}' <<< "$result")
	destination=$(awk '{print $5}' <<< "$result")
	echo "The subdomain $1 is a $record_type record that points to $destination"
}
