#!/usr/bin/env bash
# installs nginx
sudo apt -y update
sudo apt -y install nginx
sudo service ngnix start
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
