#!/usr/bin/env bash
# installs nginx
sudo apt -y update
sudo apt -y install nginx
sudo chown -R $USER:$USER /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
