#!/usr/bin/env bash
# installs nginx
sudo apt -y update
sudo apt -y install nginx
sudo service ngnix start
sudo ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.html.nginx-debian.html.bckp
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
