#!/usr/bin/env bash
# installs nginx
sudo apt -y update
sudo apt -y install nginx
sudo service ngnix start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.nginx-debian.html /var/www/html/index.html.nginx-debian.html.bckp
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '24i\        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error_404.html
sudo sed -i '25i\        error_page 404 /error_404.html;' /etc/nginx/sites-aailable/default
sudo service nginx restart
