#!/usr/bin/env bash
#configure load balancer
# installs HAProxy
echo "Installing HAProxy..."
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8.\*
echo "HAProxy Installed!"

### configure HAProxy so it can send traffic to web-01 and web-02
echo "Setting up HAProxy"
new_cofig =\
"
backend my_backend
	balance roundrobin
	server1 54.172.227.144:80 check
	server2 54.144.151.176:80 check
frontend my_frontend
	bind *:80
	default_backend my_backend
"
echo "$new_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy > /dev/null
