#!/usr/bin/env bash
#comment
counter=0
while [ $counter -lt 20 ]; do
	echo "$((counter+1))"
	case $counter in
		3)
			echo "bad luck from China";;
		8)
			echo "bad luck from Japan";;
		16)
			echo "bad luck from Italy";;
	esac
	((counter++))
done
